travis:
  secure:
    BINSTAR_TOKEN: lwYxZeXbCdyHJbjvGHWmSzwkz0RrLHOefXJQQWBizS8Evqe0zp3XcbpNjW6UtpI22VpQlyxHCKFBlXxfobMrBwJgXQVmnCGOBXaQV9vMRmdFOU6AH/ktZvBqVgW5QD0b6fmYqTuBnZ0Or/Db7WtnFd/3tt6IXpDvVPc2s5I2oWlbbHvMwrOiH1I52jCT5jtlzePuxYflZfJxmm4lvmyXSFoTwwYiBrn0iKnoGbeHMtCh7kqJUB7AHjDcDgNuk4PzLx64sDBg9EDlvaFO/4CL0X3t3gNrwXpiflrxWxTLsLSBnUVWfWVat2/Jby60SqTruC1037Km3Ctyn8Q28M3hPxMRXS3QkcIFzcodetCc/4XbHwvRsZPC3frw7jiIjWoC4O4cvYwC/QHjRe/6CUAZpCwtoY/EShbHBgvjlesM7sef4YQdFDNQC+TTrtU4zUzd41ZRTahsxp8LObiTXzHxCtoJURPTlStm5CAiqxDWwwL8Aj5pkA/umiNCokNDsJCDhZJ35KrvrHj2ZgeWoYkTM87SPgo9kFEMtMPc3vpIc1X8QgE/SdV4TtLPf7aEyEz+1GCGlyv1viMx0Fp2zNWhpV11q1bl+/qR8+u1wWzJjJ2KETetYwxHt2nONNONF/tnZQoqA8wbH87CIT4hqFYwKVOB3EPekEMe7/Y2K5cIR0c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
